USE_LOGGER: True

DATASET:
  NUM_NA_VAL: 'mode'
  NUM_NORM: 'none'
  CAT_ENCODE: false
  BATCH_SIZE: 128
  DECISION_TREE:
    MAX_COUNT: 128
    MIN_SAMPLES_BIN: 8
    DISCRETIZE_METHOD: 'none'

MODEL:
  USE_NUM_COL_NMS: true

OPTIM:
  MAX_EPOCH: 200
  LR: 1e-4
  PATIENCE: 10